spring.application.name=StockPulse

#Rapid Api keys:
rapidapi.key = 1d2a2db34emsh7a8577071358a02p14b0aajsn821e94e14eb6
rapidapi.host = apidojo-yahoo-finance-v1.p.rapidapi.com

#News API keys:
newsdata.apikey=pub_4aa12d36897b430e93f436ccd791b9c1