spring.application.name=StockPulse

#Rapid Api keys:
rapidapi.key = 1d2a2db34emsh7a8577071358a02p14b0aajsn821e94e14eb6
rapidapi.host = apidojo-yahoo-finance-v1.p.rapidapi.com

#News API keys:
newsdata.apikey=pub_4aa12d36897b430e93f436ccd791b9c1

#open router api keys:
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=mistralai/mixtral-8x7b-instruct